version: "2.27.1"
services:
  mongodb: 
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    # - MONGO_INITDB_ROOT_USERNAME=max
    #   MONGO_INITDB_ROOT_USERNAME: max
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env
    # networks:
    #   - goals-net  
    # 자동 생성되므로 굳이 할 필요는 없음
  backend: 
    build: ./backend
    # build:
      # context: ./backend
      # dockerfile: Dockerfile # 파일 이름
      # args :
      #   some-arg: 1
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend: 
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    stdin_open: true # -i
    tty: true # -t

volumes:
  data:
  logs: