FROM node:14-alpine

WORKDIR /app

ENTRYPOINT [ "npm" ]

# docker run 
#     -it 
#     -v /Users/emote2614/Downloads/docker/Sec-7/1:/app 
#     mynpm 
#     init   

# docker run 
#     -it 
#     -v /Users/emote2614/Downloads/docker/Sec-7/1:/app 
#     mynpm 
#     install express --save

